{{- if .Values.configmap.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configmap
  labels:
    {{- include "new.labels" . | nindent 4 }}
data:
  {{ toYaml .Values.configmap.data | indent 2 }}
{{- end }}