{{- if .Values.secret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: nginx-secret
  labels:
    {{- include "new.labels" . | nindent 4 }}
type: Opaque
stringData:
{{ toYaml .Values.secret.data | indent 2 }}
{{- end }}